import SmoothScroll from "@/_components/smoothScroll";
import { Aboreto, Cormorant_Garamond, Lato, Lexend_Deca, Noto_Sans, Varta} from "next/font/google";
import "./globals.css";
import Navbar from "@/_components/Navbar";

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant-sans",
  subsets: ["latin"],
  
});

const lexend = Lexend_Deca({
  subsets: ["latin"],
});
const lato = Aboreto({
  subsets: ["latin"],
weight:"400"
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable}  ${lexend.variable} ${lato.variable}  h-full antialiased`}
    >
      <body
        className={`min-h-full flex  flex-col items-center w-full  ${lato.className}`}
      >
        <SmoothScroll>
          <div className="fixed top-0 left-0 w-full z-50 pointer-events-none flex justify-center pt-4 px-4">
            <div className="pointer-events-auto flex justify-center items-center w-full "></div>
          </div>
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
