import { Aboreto, Cormorant_Garamond, Raleway } from "next/font/google";
import "./globals.css";
import MainLayout from "@/_components/MainLayout";

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant-sans",
  subsets: ["latin"],
});

const lexend = Raleway({
  subsets: ["latin"],
  weight: "600",
});
const lato = Aboreto({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable}  ${lexend.variable} ${lato.variable}  h-full antialiased`}
    >
      <body
        className={`min-h-full flex  flex-col items-center w-full  ${lexend.className}`}
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
