import { Cormorant_Garamond, Archivo_Black,Lexend_Deca } from "next/font/google";
import "./globals.css";


const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant-sans",
  subsets: ["latin"],
});

const lexend = Lexend_Deca({
  subsets: ["latin"],
});
const archivo = Archivo_Black({
  weight: "400",
  variable: "--font-archivo-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable}  ${lexend.variable}  ${archivo.variable} h-full antialiased`}
    >
      <body
        className={`min-h-full flex  flex-col items-center w-full bg-zinc-950 text-white ${lexend.className} font-semibold`}
      >
        <div className="fixed top-0 left-0 w-full z-50 pointer-events-none flex justify-center pt-4 px-4">
          <div className="pointer-events-auto flex justify-center items-center w-full ">
            
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
