export const projects = [
  {
    id: "01",
    slug: "monolith-residence-facade",
    title: "Monolith Pavilion ",
    location: "New Delhi, India",
    year: "2024",
    src: "/photos/pavillion/pavillion1.jpg",
    aspect: "h-84 md:h-auto md:aspect-square",
    gridClass: "col-span-12 md:col-span-3 md:col-start-2 md:row-start-1",
    description:
      "Designed as a sanctuary from urban noise, Monolith Pavilion balances raw concrete structures with soft, warm timber highlights. We sculpted the layout around low-slung, minimalist seating and floor-to-ceiling glass to dissolve the boundary between indoors and lush greenery, crafting an atmosphere of quiet, timeless composure.",
    gallery: [
      "/photos/pavillion/pavillion2.jpg",
      "/photos/pavillion/pavillion3.jpg",
      "/photos/pavillion/pavillion4.jpg",
      "/photos/pavillion/pavillion5.jpg",
    ],
  },
  {
    id: "02",
    slug: "echo-point-apartments",
    title: "Echo Point Apartments",
    location: "Mumbai, India",
    year: "2025",
    src: "/photos/apartment/apartment1.jpg",
    aspect: "h-84 md:h-auto md:aspect-[16/9]",
    gridClass: "col-span-12 md:col-span-5 md:col-start-7 md:row-start-1",
    description:
      "To transform a compact city footprint into an expansive retreat, we paired custom acoustic ceiling paneling with warm white oak and concealed LED channels. The result is an airy, effortless environment where morning sunlight washes across tactile surfaces, bringing elevated tranquility to daily living.",
    gallery: [
      "/photos/apartment/apartment2.jpg",
      "/photos/apartment/apartment3.jpg",
      "/photos/apartment/apartment4.jpg",
      "/photos/apartment/apartment5.jpg",
    ],
  },
  {
    id: "03",
    slug: "seabreeze-luxury-suites",
    title: "Seabreeze Coastal Suites",
    location: "Goa, India",
    year: "2026",
    src: "/photos/suite/suite1.jpg",
    aspect: "h-84 md:h-auto md:aspect-square",
    gridClass: "col-span-12 md:col-span-3 md:col-start-1 md:row-start-2",
    description:
      "Embracing the slow cadence of coastal living, we finished the walls in breathable, hand-troweled lime wash and layered natural woven textiles throughout. The layout directs every vantage point toward the horizon, allowing sea breezes and golden hour reflections to define the suite’s relaxed luxury.",
    gallery: [
      "/photos/suite/suite2.jpg",
      "/photos/suite/suite3.jpg",
      "/photos/suite/suite4.jpg",
      "/photos/suite/suite5.jpg",
    ],
  },
  {
    id: "04",
    slug: "bad-hand-coffee",
    title: "Bad Hand Cafe",
    location: "Bengaluru, India",
    year: "2024",
    src: "/photos/cafe/cafe1.jpg",
    aspect: "h-84 md:h-auto md:aspect-[4/5]",
    gridClass: "col-span-12 md:col-span-4 md:col-start-5 md:row-start-2",
    description:
      "We leaned into raw textures to build a space with authentic character—pairing exposed brickwork and hand-patinated metal with rich, solid walnut coffee bars. Soft 2700K pendant lighting casts long shadows across the seating areas, creating an inviting, unpretentious atmosphere made for conversation.",
    gallery: [
      "/photos/cafe/cafe1.jpg",
      "/photos/cafe/cafe3.jpg",
      "/photos/cafe/cafe4.jpg",
      "/photos/cafe/cafe5.jpg",
    ],
  },
  {
    id: "05",
    slug: "solstice-urban-loft",
    title: "Solstice Fine Dining Restaurant",
    location: "Kathmandu, Nepal",
    year: "2024",
    src: "/photos/restraunt/restraunt1.jpg",
    aspect: "h-84 md:h-auto md:aspect-square",
    gridClass: "col-span-12 md:col-span-3 md:col-start-10 md:row-start-2 self-end",
    description:
      "To craft an unforgettable culinary setting, we highlighted the venue's double-height volumes with custom brushed-brass accents, hand-cut stone surfaces, and sculptural dining chairs. The lighting scheme shifts throughout the evening to continuously refine the drama of the room.",
    gallery: [
      "/photos/restraunt/restraunt2.jpg",
      "/photos/restraunt/restraunt3.jpg",
      "/photos/restraunt/restraunt4.jpg",
      "/photos/restraunt/restraunt5.jpg",
    ],
  },
  {
    id: "06",
    slug: "terracotta-dining-lounge",
    title: "Terracotta Cocktail Lounge",
    location: "Galle, Sri Lanka",
    year: "2025",
    src: "/photos/lounge/lounge1.jpg",
    aspect: "h-84 md:h-auto md:aspect-[16/9]",
    gridClass: "col-span-12 md:col-span-5 md:col-start-2 md:row-start-3",
    description:
      "Centering around tactile warmth, we wrapped this lounge in hand-tinted terracotta plaster, plush curved velvet seating, and smooth micro-cement floors. Deep indirect uplighting amplifies the rich textures, wrapping guests in an intimate, moody hospitality experience.",
    gallery: [
      "/photos/lounge/lounge2.jpg",
      "/photos/lounge/lounge3.jpg",
      "/photos/lounge/lounge4.jpg",
      "/photos/lounge/lounge5.jpg",
    ],
  },
  {
    id: "07",
    slug: "aura-glasshouse-pavilion",
    title: "Aura Creative Studio ",
    location: "Gurugram, India",
    year: "2026",
    src: "/photos/office/office1.jpg",
    aspect: "h-84 md:h-auto md:aspect-square",
    gridClass: "col-span-12 md:col-span-4 md:col-start-8 md:row-start-3",
    description:
      "Designed to foster focus and calm, we replaced rigid corporate cubicles with double-glazed acoustic partitions, warm timber desks, and integrated indoor greenery. The open spatial flow lets natural light penetrate deep into the floor plate while preserving individual privacy.",
    gallery: [
      "/photos/office/office2.jpg",
      "/photos/office/office3.jpg",
      "/photos/office/office4.jpg",
      "/photos/office/office5.jpg",
    ],
  },
  {
    id: "08",
    slug: "sunset-ridge-villas",
    title: "Sunset Ridge  Villa",
    location: "Udaipur, India",
    year: "2025",
    src: "/photos/villa/villa1.jpg",
    aspect: "h-84 md:h-auto md:aspect-[4/5]",
    gridClass:
      "col-span-12 md:col-span-4 md:col-start-5 md:row-start-4",
    description:
      "A dialogue between regional heritage and modern spatial design. We integrated locally quarried stone masonry, central water courtyards, and handcrafted teak woodwork to anchor the villa into the landscape, producing a grounded retreat that glows under the evening sun.",
    gallery: [
      "/photos/villa/villa2.jpg",
      "/photos/villa/villa3.jpg",
      "/photos/villa/villa4.jpg",
      "/photos/villa/villa5.jpg",
    ],
  },
];
