export const projects = [
  {
    id: "01",
    slug: "monolith-residence-facade",
    title: "Monolith Residence Façade",
    location: "Oslo, Norway",
    year: "2024",
    src: "/workImgs/workImg1.jpg",
    aspect: "h-84 md:h-auto md:aspect-square",
    gridClass: "col-span-12 md:col-span-3 md:col-start-2 md:row-start-1",
    description:
      "A bold, structural façade project combining raw concrete finishes with warm timber accents to create a seamless indoor-outdoor architectural statement.",
    gallery: [
      "/workImgs/workImg1.jpg",
      "/workImgs/workImg2.jpg",
      "/workImgs/workImg3.jpg",
    ],
  },
  {
    id: "02",
    slug: "echo-point-apartments",
    title: "Echo Point Apartments",
    location: "Sydney, Australia",
    year: "2025",
    src: "/workImgs/workImg2.jpg",
    aspect: "h-84 md:h-auto md:aspect-[16/9]",
    gridClass: "col-span-12 md:col-span-5 md:col-start-7 md:row-start-1",
    description:
      "Multi-family residential living engineered around natural light, acoustic isolation, and textured minimalism.",
    gallery: ["/workImgs/workImg2.jpg", "/workImgs/workImg4.jpg"],
  },
  {
    id: "03",
    slug: "seabreeze-luxury-suites",
    title: "Seabreeze Luxury Suites",
    location: "Bali, Indonesia",
    year: "2026",
    src: "/workImgs/workImg3.jpg",
    aspect: "h-84 md:h-auto md:aspect-square",
    gridClass: "col-span-12 md:col-span-3 md:col-start-1 md:row-start-2",
    description:
      "High-end coastal suites designed with lime-washed walls, light oak, and expansive open-plan views.",
    gallery: ["/workImgs/workImg3.jpg", "/workImgs/workImg5.jpg"],
  },
  {
    id: "04",
    slug: "bad-hand-coffee",
    title: "Bad Hand Coffee",
    location: "London, UK",
    year: "2024",
    src: "/workImgs/workImg4.jpg",
    aspect: "h-84 md:h-auto md:aspect-[4/5]",
    gridClass: "col-span-12 md:col-span-4 md:col-start-5 md:row-start-2",
    description:
      "An industrial coffee shop interior utilizing exposed brickwork, patinated metal, and custom joinery.",
    gallery: ["/workImgs/workImg4.jpg", "/workImgs/workImg1.jpg"],
  },
  {
    id: "05",
    slug: "sunset-ridge-villas",
    title: "Sunset Ridge Villas",
    location: "Kyoto, Japan",
    year: "2025",
    src: "/workImgs/workImg5.jpg",
    aspect: "h-84 md:h-auto md:aspect-square",
    gridClass:
      "col-span-12 md:col-span-3 md:col-start-10 md:row-start-2 self-end",
    description:
      "A collection of hillside villas emphasizing terraced stone masonry, private courtyards, and organic interior elements.",
    gallery: ["/workImgs/workImg5.jpg", "/workImgs/workImg2.jpg"],
  },
  {
    id: "06",
    slug: "terracotta-dining-lounge",
    title: "Terracotta Dining Lounge",
    location: "Milan, Italy",
    year: "2025",
    src: "/workImgs/workImg6.jpg",
    aspect: "h-84 md:h-auto md:aspect-[16/9]",
    gridClass: "col-span-12 md:col-span-5 md:col-start-2 md:row-start-3",
    description:
      "A warm dining environment focused on earthy ceramic tones, sculptural ceiling plasterwork, and ambient indirect lighting.",
    gallery: ["/workImgs/workImg6.jpg", "/workImgs/workImg3.jpg"],
  },
  {
    id: "07",
    slug: "aura-glasshouse-pavilion",
    title: "Aura Glasshouse Pavilion",
    location: "Zurich, Switzerland",
    year: "2026",
    src: "/workImgs/workImg7.jpg",
    aspect: "h-84 md:h-auto md:aspect-square",
    gridClass: "col-span-12 md:col-span-4 md:col-start-8 md:row-start-3",
    description:
      "A minimalist glass and steel pavilion built to reflect natural alpine surroundings with clean structural transparency.",
    gallery: ["/workImgs/workImg7.jpg", "/workImgs/workImg1.jpg"],
  },
  {
    id: "08",
    slug: "solstice-urban-loft",
    title: "Solstice Urban Loft",
    location: "Berlin, Germany",
    year: "2024",
    src: "/workImgs/workImg8.jpg",
    aspect: "h-84 md:h-auto md:aspect-[4/5]",
    gridClass: "col-span-12 md:col-span-4 md:col-start-5 md:row-start-4",
    description:
      "A converted industrial space featuring double-height ceilings, bespoke matte steel staircases, and raw stone surfaces.",
    gallery: ["/workImgs/workImg8.jpg", "/workImgs/workImg4.jpg"],
  },
];